### ISSUE TITLE
undefined symbol: __atomic_load_8

### ISSUE THREAD

**Issue by gizmo3845** [erikest/libgrpc_csharp_ext#2]
Hi,

I've managed to compile it but when I run my c# .Net core 3.1 program, I get:

dotnet: symbol lookup error: /app/libgrpc_csharp_ext.x86.so: undefined symbol: __atomic_load_8

Do you have an idea on how to solve this ?

Thanks

**Comment by sherlock1982** [comment]
Because it's missing libatomic reference (that is required for this function on ARM).

Author can add it in his toolchain with:
`add_link_options(-latomic)`

In the meantime you can workaround it as mentioned here with LD_PRELOAD:
https://github.com/piwheels/packages/issues/59

**Comment by erikest** [comment]
Thank you 👍 

I was not aware of that dependency, but then I hadn't reviewed what had changed when I last built this, I just pulled latest and let rebuilt using the toolchain I had set up previously.

Thanks for the quick pointer @sherlock1982 (my birth year brother).  I will update my article, source files and nuget soon :)

**Comment by erikest** [comment]
I didn't update things soon enough, so thank you @dylanbmckinney for your PR to get this working!
